language: node_js
node_js:
- '0.10'
before_install:
- npm install coffee-script
before_script:
- ./node_modules/.bin/cake archive
deploy:
  provider: releases
  api_key:
    secure: N8Ax7oBlgqeJLi5h9nwE42SekB1TBQ8BJc/Cy+JdxilX9nkwcd7K3TAPRCWUtsREFO/nH4lXi5A8Lh5T2AAw+v0eMtYmZZuXZtmLLOaNcQdQOTzzYFRY9lbWBD76nUhjJ56/rU6glPuxHPkpY+S9yc0JmL2i+lSNhUX+uJkt0c8=
  file: build/SwiftAlamofireCodeGenerator.zip
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
    repo: luckymarmot/Paw-SwiftAlamofireCodeGenerator
